### ISSUE TITLE
raise ImgurClientError('JSON decoding of response failed.') imgurpython.helpers.error.ImgurClientError: JSON decoding of response failed.

### ISSUE THREAD

**Issue by monajalal** [Imgur/imgurpython#74]
What should I do when I get the following error in the middle of my running code? What's the cause for it?

```
Traceback (most recent call last):
  File "download.py", line 14, in <module>
    search = imgur_client.gallery_search('cat', window='all', sort='time', page=i)
  File "/usr/local/lib/python2.7/dist-packages/imgurpython/client.py", line 531, in gallery_search
    response = self.make_request('GET', 'gallery/search/%s/%s/%s' % (sort, window, page), data)
  File "/usr/local/lib/python2.7/dist-packages/imgurpython/client.py", line 158, in make_request
    raise ImgurClientError('JSON decoding of response failed.')
imgurpython.helpers.error.ImgurClientError: JSON decoding of response failed.

```

**Comment by Backscratcher** [comment]
1. I think there is a problem with Your `image_file_name`, try with something like this: 
`image_file_name = 'images/{0}.{1}'.format(search[i].id, type)` <- but still you need to parse type because it comes in format like "image/gif" 
2. It is not the only issue, I ran your code and it will fail on objects like `GalleryAlbum` - because it has no type.
wrap your code with try/except like:
`try:
 your code here
except Exception:
    pass
`
 or make an if for it handle this situation

**Comment by monajalal** [comment]
I get similar error here:
http://stackoverflow.com/questions/40115380/imgurpython-helpers-error-imgurclientratelimiterror-rate-limit-exceeded
The previous one was fixed
